source 'https://github.com/tjcjc/Specs.git'
source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'MDictParser_Example' do
  pod 'MDictParser', :path => '../'

  target 'MDictParser_Tests' do
    inherit! :search_paths

    pod 'Quick', '~> 1.2.0'
    pod 'Nimble', '~> 7.0'
  end
end
